# Report

This report is automatically generated by {{ foo['bar'] }}.

## Summary

{% if anomaly != [] %}
    {%- set num = namespace(value=0) -%}
    {%- for item in anomaly -%}
        {%- if item['obj']|length > 0 -%}
            {%- set num.value = num.value + 1 -%}
        {%- endif -%}
    {%- endfor -%}
    There are anomalies in {{ num.value }} pieces of time slice.
{%- else %}
    Everything runs well.
{%- endif %}

## Details

{% for item in sort_corr -%}
    {% if item|length > 0  %}
* No. {{ loop.index }} piece of time slice:
            {% for obj in item %}
  * Objective signal: {{ obj['name'] }}, Correlation: 
                {% for can in obj['corre'][:3] %}
    * Name: {{ can['name'] }} , Corr: {{ can['corr'] }}
                {%- endfor %}
            {%- endfor %}
    {%- endif %}
{%- endfor %}

## Snapshots

{% for item in pics -%}
* ![pic]({{ item }})
{% endfor %}
